version: '3.8'
services:
  project-service-db:
    image: "postgres:latest"
    container_name: project-service-db
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "25432:5432"
    volumes:
      - project-service-db-data:/var/lib/postgresql/data
volumes:
  project-service-db-data: