version: '3.8'
services:
  project-service-elasticsearch:
    image: elasticsearch:7.10.1
    container_name: project-service-elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=odfe-node
      - discovery.seed_hosts=odfe-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "19200:9200"
      - "19600:9600"
    networks:
      - project-service-net
volumes:
  elasticsearch_data:
networks:
  project-service-net: